services:
  - type: web
    name: mimiportfolio
    env: node
    buildCommand: npm install && npm run build && mkdir -p build && ls -la build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
